dependencies:
- name: demo204
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.82
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.82
- name: godemo17
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: nodey31
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: nodey37
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
